var app = angular.module('ClientWsIframe', ['ngRoute','ngCookies']);
app.controller('ClientController', ['$scope','$rootScope',
    function($scope, $rootScope) {
        $scope.userList = [
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'},
            {id:1, type:0,name:'user1'}
        ];
        $scope.conversationContent = [
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'},
            {id:1, timestamp: "22:23:00", content:'some random text'}
        ];
    }
]);